package com.powerx.renpower.utilitywebservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-19T00:06:43.536-05:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://webservice.utilitywebservice.renpower.powerx.com/", name = "ServicePlanWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicePlanWS {

    @WebMethod
    @RequestWrapper(localName = "getServicePlan", targetNamespace = "http://webservice.utilitywebservice.renpower.powerx.com/", className = "com.powerx.renpower.utilitywebservice.GetServicePlan")
    @ResponseWrapper(localName = "getServicePlanResponse", targetNamespace = "http://webservice.utilitywebservice.renpower.powerx.com/", className = "com.powerx.renpower.utilitywebservice.GetServicePlanResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.powerx.renpower.utilitywebservice.ServicePlan> getServicePlan();
}
